import { mkdtempSync, rmSync, existsSync, readFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import {
  runDependencySync,
  DEPENDENCY_SYNC_DEFAULT_TIMEOUT_MS,
} from '../dist/handlers/dependency-sync.js';

// ---------------------------------------------------------------------------
// Sequence runner: each call to run() consumes one queued result.
// ---------------------------------------------------------------------------
function sequenceRunner(steps) {
  const calls = [];
  let i = 0;
  return {
    calls,
    run(cmd, args, opts) {
      const result = steps[i] ?? { stdout: '', stderr: 'unexpected call', exitCode: 1 };
      calls.push({ cmd, args, opts, result });
      i++;
      return result;
    },
  };
}

const CONFIG = (overrides = {}) => ({
  enabled: true,
  triggerPaths: ['package.json'],
  expectedOutputs: ['package-lock.json'],
  command: 'npm install --package-lock-only --ignore-scripts',
  timeoutMs: 120000,
  ...overrides,
});

let tmpDir;
let artifactDir;

beforeEach(() => {
  tmpDir = mkdtempSync(join(tmpdir(), 'dep-sync-test-'));
  artifactDir = tmpDir;
});

afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

describe('runDependencySync — no-op cases', () => {
  test('undefined config is a no-op and runs no commands', () => {
    const runner = sequenceRunner([]);
    const out = runDependencySync(runner, undefined, '/repo', artifactDir);
    expect(out).toEqual({ ran: false, passed: true, changedTriggerPaths: [], producedExpectedOutputs: [] });
    expect(runner.calls).toHaveLength(0);
  });

  test('disabled config is a no-op and runs no commands', () => {
    const runner = sequenceRunner([]);
    const out = runDependencySync(runner, CONFIG({ enabled: false }), '/repo', artifactDir);
    expect(out.ran).toBe(false);
    expect(runner.calls).toHaveLength(0);
  });

  test('does not run the sync command when no trigger path changed', () => {
    const runner = sequenceRunner([
      { stdout: ' M src/foo.ts\n', stderr: '', exitCode: 0 }, // git status — only an unrelated file changed
    ]);
    const out = runDependencySync(runner, CONFIG(), '/repo', artifactDir);
    expect(out.ran).toBe(false);
    expect(out.changedTriggerPaths).toEqual([]);
    // Only the status probe ran; the npm command was never spawned.
    expect(runner.calls).toHaveLength(1);
    expect(runner.calls[0]).toMatchObject({ cmd: 'git', args: ['status', '--porcelain'] });
  });
});

describe('runDependencySync — stale-output resync after a repair reverts the manifest', () => {
  test('forces a resync when a prior sync ran and an expected output is still dirty with no trigger change', () => {
    const runner = sequenceRunner([
      // git status (before): a repair reverted package.json, so only the lockfile
      // (regenerated by the earlier sync) is still dirty — no trigger path changed.
      { stdout: ' M package-lock.json\n', stderr: '', exitCode: 0 },
      { stdout: 'regenerated lockfile', stderr: '', exitCode: 0 }, // npm install (forced resync)
      { stdout: '', stderr: '', exitCode: 0 },                     // git status (after): lockfile back in sync
    ]);
    const previousOutcome = {
      ran: true,
      passed: true,
      changedTriggerPaths: ['package.json'],
      producedExpectedOutputs: ['package-lock.json'],
    };
    const out = runDependencySync(runner, CONFIG(), '/repo', artifactDir, previousOutcome);
    expect(out.ran).toBe(true);
    expect(out.passed).toBe(true);
    expect(out.resyncedStaleOutputs).toBe(true);
    expect(out.changedTriggerPaths).toEqual([]);
    // The exact configured command ran even though no trigger path changed.
    const npmCall = runner.calls[1];
    expect(npmCall.cmd).toBe('npm');
    expect(npmCall.args).toEqual(['install', '--package-lock-only', '--ignore-scripts']);
  });

  test('does NOT resync without a prior sync, even if an expected output looks dirty', () => {
    const runner = sequenceRunner([
      { stdout: ' M package-lock.json\n', stderr: '', exitCode: 0 }, // git status — lockfile dirty, no trigger
    ]);
    // No previousOutcome: the first call must keep its no-op behavior so an
    // agent-authored change is never overwritten by an unsolicited sync.
    const out = runDependencySync(runner, CONFIG(), '/repo', artifactDir);
    expect(out.ran).toBe(false);
    expect(out.changedTriggerPaths).toEqual([]);
    expect(out.resyncedStaleOutputs).toBeUndefined();
    expect(runner.calls).toHaveLength(1);
  });

  test('does NOT resync when the prior sync ran but no expected output is dirty', () => {
    const runner = sequenceRunner([
      { stdout: ' M src/foo.ts\n', stderr: '', exitCode: 0 }, // git status — unrelated change only
    ]);
    const previousOutcome = {
      ran: true,
      passed: true,
      changedTriggerPaths: ['package.json'],
      producedExpectedOutputs: ['package-lock.json'],
    };
    const out = runDependencySync(runner, CONFIG(), '/repo', artifactDir, previousOutcome);
    expect(out.ran).toBe(false);
    expect(runner.calls).toHaveLength(1);
  });
});

describe('runDependencySync — runs the command on trigger change', () => {
  test('runs the exact configured command when a trigger path changed', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },                       // git status (before)
      { stdout: 'updated lockfile', stderr: '', exitCode: 0 },                        // npm install ...
      { stdout: ' M package.json\n M package-lock.json\n', stderr: '', exitCode: 0 }, // git status (after)
    ]);
    const out = runDependencySync(runner, CONFIG(), '/repo', artifactDir);
    expect(out).toMatchObject({
      ran: true,
      passed: true,
      command: 'npm install --package-lock-only --ignore-scripts',
      changedTriggerPaths: ['package.json'],
      producedExpectedOutputs: ['package-lock.json'],
    });
    // The npm command is tokenized exactly from the configured string.
    const npmCall = runner.calls[1];
    expect(npmCall.cmd).toBe('npm');
    expect(npmCall.args).toEqual(['install', '--package-lock-only', '--ignore-scripts']);
  });

  test('bounds the command runtime and output', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },
      { stdout: 'ok', stderr: '', exitCode: 0 },
      { stdout: ' M package-lock.json\n', stderr: '', exitCode: 0 },
    ]);
    runDependencySync(runner, CONFIG({ timeoutMs: 45000 }), '/repo', artifactDir);
    const npmCall = runner.calls[1];
    expect(npmCall.opts.timeout).toBe(45000);
    expect(npmCall.opts.maxBuffer).toBeGreaterThan(1024 * 1024);
  });

  test('falls back to the default timeout when timeoutMs is omitted', () => {
    const { timeoutMs, ...noTimeout } = CONFIG();
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },
      { stdout: 'ok', stderr: '', exitCode: 0 },
      { stdout: '', stderr: '', exitCode: 0 },
    ]);
    runDependencySync(runner, noTimeout, '/repo', artifactDir);
    expect(runner.calls[1].opts.timeout).toBe(DEPENDENCY_SYNC_DEFAULT_TIMEOUT_MS);
  });

  test('a no-op (already-synced) lockfile is still a success', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 }, // trigger changed
      { stdout: 'up to date', stderr: '', exitCode: 0 },        // npm install — no lockfile change
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 }, // git status (after) — lockfile unchanged
    ]);
    const out = runDependencySync(runner, CONFIG(), '/repo', artifactDir);
    expect(out.passed).toBe(true);
    expect(out.producedExpectedOutputs).toEqual([]);
  });

  test('writes a bounded dependency-sync.log artifact', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },
      { stdout: 'resolve output', stderr: 'a warning', exitCode: 0 },
      { stdout: ' M package-lock.json\n', stderr: '', exitCode: 0 },
    ]);
    runDependencySync(runner, CONFIG(), '/repo', artifactDir);
    const logPath = join(artifactDir, 'dependency-sync.log');
    expect(existsSync(logPath)).toBe(true);
    expect(readFileSync(logPath, 'utf8')).toContain('resolve output');
  });
});

describe('runDependencySync — failure', () => {
  test('non-zero exit is surfaced as a bounded failure (no after-status probe)', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },                          // git status (before)
      { stdout: '', stderr: 'npm ERR! 404 Not Found: no-such-pkg', exitCode: 1 },        // npm install fails
    ]);
    const out = runDependencySync(runner, CONFIG(), '/repo', artifactDir);
    expect(out.ran).toBe(true);
    expect(out.passed).toBe(false);
    expect(out.failure).toMatchObject({ kind: 'exit', exitCode: 1 });
    expect(out.failure.output).toContain('404 Not Found');
    // It must NOT probe git status again after a failed command.
    expect(runner.calls).toHaveLength(2);
  });

  test('an empty configured command string is a no-op (does not spawn an empty process)', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },
    ]);
    const out = runDependencySync(runner, CONFIG({ command: '   ' }), '/repo', artifactDir);
    expect(out.ran).toBe(false);
    expect(out.changedTriggerPaths).toEqual(['package.json']);
    expect(runner.calls).toHaveLength(1);
  });
});

describe('runDependencySync — safe mode (lifecycle scripts)', () => {
  test('refuses a lifecycle-running command when allowLifecycleScripts is omitted', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 }, // trigger changed
    ]);
    // `npm install` (no --ignore-scripts) would run lifecycle scripts.
    const out = runDependencySync(runner, CONFIG({ command: 'npm install' }), '/repo', artifactDir);
    expect(out.ran).toBe(false);
    expect(out.passed).toBe(false);
    expect(out.changedTriggerPaths).toEqual(['package.json']);
    expect(out.failure).toMatchObject({ kind: 'unsafe-command', exitCode: 0 });
    expect(out.failure.output).toContain('allowLifecycleScripts');
    // Only the status probe ran; the unsafe command was never spawned.
    expect(runner.calls).toHaveLength(1);
    expect(runner.calls.some((c) => c.cmd === 'npm')).toBe(false);
  });

  test('refuses a lifecycle-running command when allowLifecycleScripts is false', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },
    ]);
    const out = runDependencySync(
      runner,
      CONFIG({ command: 'npm install', allowLifecycleScripts: false }),
      '/repo',
      artifactDir,
    );
    expect(out.ran).toBe(false);
    expect(out.passed).toBe(false);
    expect(out.failure.kind).toBe('unsafe-command');
    expect(runner.calls).toHaveLength(1);
  });

  test('runs a lifecycle-running command when allowLifecycleScripts is true', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },   // trigger changed
      { stdout: 'installed', stderr: '', exitCode: 0 },           // npm install
      { stdout: ' M package-lock.json\n', stderr: '', exitCode: 0 }, // git status (after)
    ]);
    const out = runDependencySync(
      runner,
      CONFIG({ command: 'npm install', allowLifecycleScripts: true }),
      '/repo',
      artifactDir,
    );
    expect(out.ran).toBe(true);
    expect(out.passed).toBe(true);
    const npmCall = runner.calls[1];
    expect(npmCall.cmd).toBe('npm');
    expect(npmCall.args).toEqual(['install']);
  });

  test('refuses a project-script runner that carries a dummy --ignore-scripts arg', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 }, // trigger changed
    ]);
    // `npm run build --ignore-scripts` still executes the agent-editable `build`
    // script; the flag only suppresses npm's own pre/post hooks.
    const out = runDependencySync(
      runner,
      CONFIG({ command: 'npm run build --ignore-scripts' }),
      '/repo',
      artifactDir,
    );
    expect(out.ran).toBe(false);
    expect(out.passed).toBe(false);
    expect(out.failure.kind).toBe('unsafe-command');
    // Only the status probe ran; the script runner was never spawned.
    expect(runner.calls).toHaveLength(1);
    expect(runner.calls.some((c) => c.cmd === 'npm')).toBe(false);
  });

  test('refuses a shell wrapper that merely carries an --ignore-scripts arg', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },
    ]);
    const out = runDependencySync(
      runner,
      CONFIG({ command: './wrapper.sh --ignore-scripts' }),
      '/repo',
      artifactDir,
    );
    expect(out.ran).toBe(false);
    expect(out.passed).toBe(false);
    expect(out.failure.kind).toBe('unsafe-command');
    expect(runner.calls).toHaveLength(1);
  });

  test('refuses an npm install missing --package-lock-only (mutates node_modules)', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },
    ]);
    // `npm install --ignore-scripts` skips scripts but still populates node_modules,
    // so it is not a recognized lockfile-only shape.
    const out = runDependencySync(
      runner,
      CONFIG({ command: 'npm install --ignore-scripts' }),
      '/repo',
      artifactDir,
    );
    expect(out.ran).toBe(false);
    expect(out.failure.kind).toBe('unsafe-command');
    expect(runner.calls).toHaveLength(1);
  });

  test('refuses a command that negates a required safe-mode flag with a later duplicate', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },
    ]);
    // The required flag is present but a later `--ignore-scripts=false` flips the
    // effective value off; npm uses the last boolean, so this would run lifecycle
    // scripts. A presence-only check would wrongly accept it (issue #290 review).
    const out = runDependencySync(
      runner,
      CONFIG({
        command: 'npm install --package-lock-only --ignore-scripts --ignore-scripts=false',
      }),
      '/repo',
      artifactDir,
    );
    expect(out.ran).toBe(false);
    expect(out.passed).toBe(false);
    expect(out.failure.kind).toBe('unsafe-command');
    // Only the status probe ran; the negated command was never spawned.
    expect(runner.calls).toHaveLength(1);
    expect(runner.calls.some((c) => c.cmd === 'npm')).toBe(false);
  });

  test('refuses a command that negates a required flag via --no- form', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },
    ]);
    const out = runDependencySync(
      runner,
      CONFIG({
        command: 'npm install --package-lock-only --ignore-scripts --no-ignore-scripts',
      }),
      '/repo',
      artifactDir,
    );
    expect(out.ran).toBe(false);
    expect(out.failure.kind).toBe('unsafe-command');
    expect(runner.calls).toHaveLength(1);
  });

  test('still runs a no-lifecycle-script command (with --ignore-scripts) without opt-in', () => {
    const runner = sequenceRunner([
      { stdout: ' M package.json\n', stderr: '', exitCode: 0 },
      { stdout: 'ok', stderr: '', exitCode: 0 },
      { stdout: ' M package-lock.json\n', stderr: '', exitCode: 0 },
    ]);
    const out = runDependencySync(runner, CONFIG(), '/repo', artifactDir);
    expect(out.ran).toBe(true);
    expect(out.passed).toBe(true);
  });
});
