/**
 * Human Gate Decision Summary formatter (issue #552).
 *
 * Generates a markdown PR comment posted as a sticky comment when an AI review
 * passes and the task transitions to the human merge gate (`ready_for_human`).
 * The comment answers the four human-reviewer questions: what, how, risks, and
 * AI decisions/assumptions.
 *
 * Uses a distinct marker from `PR_SUMMARY_MARKER` so the two sticky comments
 * are managed independently — updating one never clobbers the other.
 */

import type { DiffClassification } from "./review-diff-context.js";

/** Stable HTML comment marker for the sticky human-gate decision summary. */
export const HUMAN_GATE_MARKER = "<!-- n8n-ai-human-gate -->";

export interface HumanGateSummaryInput {
  issueNumber: number;
  /** Issue title — omitted when the work-item is on a private surface. */
  issueTitle?: string;
  prNumber?: number;
  branch?: string;
  phase: string;
  phaseResult: string;
  runId: string;
  diffClassification?: DiffClassification;
  /** Names of verification commands that ran. */
  verificationNames?: string[];
  /** Whether verification passed overall. */
  verificationPassed?: boolean;
  /** Agent ID that performed the review (e.g. "claude", "codex"). */
  reviewAgentUsed?: string;
  /**
   * Deterministic classifier reason for the review outcome (safe to publish:
   * generated by `classifyReviewOutput`, not raw AI prose).
   */
  classifierReason?: string;
  /** Resolved agent profile for run metadata. */
  resolvedProfile?: Record<string, unknown>;
  durationMs?: number;
}

const FILE_LIST_CAP = 10;

function renderFileList(files: string[], max = FILE_LIST_CAP): string {
  if (files.length === 0) return "—";
  const shown = files.slice(0, max);
  const overflow = files.length - shown.length;
  const base = shown.map((f) => `\`${f}\``).join(", ");
  return overflow > 0 ? `${base} _(+${overflow} more)_` : base;
}

function agentLabel(agentId: string): string {
  if (agentId === "claude") return "Claude (Anthropic)";
  if (agentId === "codex") return "Codex (OpenAI)";
  if (agentId === "gemini" || agentId === "agy") return "Gemini (Google)";
  return agentId;
}

function formatDurationMs(ms: number): string {
  const totalSeconds = Math.round(ms / 1000);
  if (totalSeconds < 60) return `${totalSeconds}s`;
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return seconds > 0 ? `${minutes}m ${seconds}s` : `${minutes}m`;
}

/**
 * Render the full Human Gate Decision Summary body including the HTML marker.
 * The marker must be present so `upsertStickyPrComment` can find and replace
 * this comment on subsequent review passes without duplicating it.
 */
export function renderHumanGateSummary(input: HumanGateSummaryInput): string {
  const {
    issueNumber,
    issueTitle,
    prNumber,
    branch,
    phase,
    phaseResult,
    runId,
    diffClassification,
    verificationNames = [],
    verificationPassed,
    reviewAgentUsed,
    classifierReason,
    resolvedProfile,
    durationMs,
  } = input;

  const lines: string[] = [HUMAN_GATE_MARKER, ""];

  lines.push("## Human Gate Decision Summary", "");

  // Issue / PR header
  const titleSuffix = issueTitle ? ` — ${issueTitle}` : "";
  lines.push(`**Issue #${issueNumber}**${titleSuffix}`);
  if (prNumber !== undefined) {
    const branchNote = branch ? ` (branch: \`${branch}\`)` : "";
    lines.push(`**PR #${prNumber}**${branchNote}`);
  }
  lines.push("");

  // Implementation intent
  lines.push("### Implementation Intent");
  if (issueTitle) {
    lines.push(
      `This PR addresses Issue #${issueNumber} — ${issueTitle}. ` +
        `Refer to the linked issue for full requirements and acceptance criteria.`,
    );
  } else {
    lines.push(
      `This PR addresses Issue #${issueNumber}. ` +
        `Refer to the linked issue for full requirements and acceptance criteria.`,
    );
  }
  lines.push("");

  // Implementation approach (derived from diff classification)
  lines.push("### Implementation Approach");
  if (diffClassification) {
    const { added, modified, deleted, renamed } = diffClassification;
    const totalFiles = added.length + modified.length + deleted.length + renamed.length;
    if (totalFiles === 0) {
      lines.push("No file changes detected.");
    } else {
      if (added.length > 0)
        lines.push(`- **Added (${added.length})**: ${renderFileList(added)}`);
      if (modified.length > 0)
        lines.push(`- **Modified (${modified.length})**: ${renderFileList(modified)}`);
      if (deleted.length > 0)
        lines.push(`- **Deleted (${deleted.length})**: ${renderFileList(deleted)}`);
      if (renamed.length > 0)
        lines.push(
          `- **Renamed (${renamed.length})**: ${renderFileList(renamed.map((r) => `${r.from} → ${r.to}`))}`,
        );
    }
  } else {
    lines.push("unknown — diff classification unavailable for this review agent.");
  }
  lines.push("");

  // Verification summary
  lines.push("### Verification");
  if (verificationPassed !== undefined) {
    const status = verificationPassed ? "✅ passed" : "❌ failed";
    const names = verificationNames.length > 0 ? verificationNames.join(", ") : "verification";
    lines.push(`${names}: ${status}`);
  } else {
    lines.push("unknown — not recorded for this phase.");
  }
  lines.push("");

  // Risk summary
  lines.push("### Risk Summary");
  const risks: string[] = [];
  if (diffClassification) {
    const { guardrail } = diffClassification;
    if (guardrail.deleted.length > 0) {
      risks.push(
        `⚠️ Guardrail/tooling file(s) deleted: ${renderFileList(guardrail.deleted)} — deletion requires justification tied to the issue scope.`,
      );
    }
    if (guardrail.added.length > 0) {
      risks.push(
        `Guardrail/tooling file(s) added: ${renderFileList(guardrail.added)} — verify intent.`,
      );
    }
    if (guardrail.modified.length > 0) {
      risks.push(
        `Guardrail/tooling file(s) modified: ${renderFileList(guardrail.modified)} — verify intent.`,
      );
    }
    if (guardrail.renamed.length > 0) {
      risks.push(
        `Guardrail/tooling file(s) renamed: ${renderFileList(guardrail.renamed.map((r) => `${r.from} → ${r.to}`))} — verify intent.`,
      );
    }
  }
  if (risks.length > 0) {
    for (const r of risks) lines.push(`- ${r}`);
  } else if (diffClassification) {
    lines.push("- None detected by the workflow.");
  } else {
    lines.push(
      "- Diff classification unavailable — guardrail/tooling checks did not run; review the diff manually.",
    );
  }
  lines.push("- CI/external check status: unknown — not queried by the workflow.");
  lines.push(
    "- Behavior changes, migrations, concurrency/workflow risks, and security/privacy concerns are not audited by this summary — review the diff.",
  );
  lines.push("");

  // AI decisions and assumptions
  lines.push("### AI Decisions and Assumptions");
  if (classifierReason) {
    lines.push(`- Review outcome: ${classifierReason}`);
  }
  if (reviewAgentUsed) {
    lines.push(`- Review agent: ${agentLabel(reviewAgentUsed)}`);
  }
  if (resolvedProfile) {
    const provider = typeof resolvedProfile.provider === "string" ? resolvedProfile.provider : undefined;
    const model = typeof resolvedProfile.model === "string" ? resolvedProfile.model : undefined;
    const effort =
      typeof resolvedProfile.effort === "string"
        ? resolvedProfile.effort
        : typeof resolvedProfile.reviewStrength === "string"
          ? resolvedProfile.reviewStrength
          : undefined;
    if (provider) lines.push(`- Provider: ${provider}`);
    // "cli-default" is the literal model value an unconfigured Codex or Gemini
    // profile sets (Claude always resolves a real model name) — say so explicitly
    // rather than omitting the line (issue #609: distinguishable in metadata).
    if (model) {
      lines.push(`- Model: ${model === "cli-default" ? "CLI default (compatibility mode)" : model}`);
    }
    if (effort) lines.push(`- Effort/strength: ${effort}`);
  }
  lines.push(
    "- Scope choices, inferred behavior, and alternatives considered during implementation are not explicitly captured — inspect the diff and issue requirements.",
  );
  lines.push("");

  // Go / No-go checklist
  lines.push("### Go / No-go Checklist");
  lines.push("- [ ] Implementation intent correctly matches the issue requirements");
  lines.push("- [ ] All files changed are expected and in scope");
  const guardrailTouched =
    diffClassification !== undefined &&
    (diffClassification.guardrail.added.length > 0 ||
      diffClassification.guardrail.modified.length > 0 ||
      diffClassification.guardrail.deleted.length > 0 ||
      diffClassification.guardrail.renamed.length > 0);
  if (guardrailTouched) {
    lines.push("- [ ] Guardrail/tooling file changes are justified");
  }
  lines.push("- [ ] Verification has passed (see above)");
  lines.push("- [ ] Risk areas and behavior changes have been reviewed");
  lines.push("- [ ] Ready to merge");
  lines.push("");

  // Footer
  const durNote = durationMs !== undefined ? ` | Duration: ${formatDurationMs(durationMs)}` : "";
  lines.push("---");
  lines.push(`_Phase: ${phase} | Result: ${phaseResult} | Run: ${runId}${durNote}_`);

  return lines.join("\n");
}
